import { Building2, Calculator, Palette, Megaphone, Code, FileCheck, Users, TrendingUp, DollarSign, Scale } from 'lucide-react'

export const servicesData = [
  {
    id: "company-formation",
    title: "Company Formation & Registration",
    slug: "company-formation",
    description: "Start your business journey on the right foot with our comprehensive company formation services.",
    longDescription: "We simplify the complex process of company registration in India. Whether you're a solo entrepreneur or a group of founders, we help you choose the right business structure and handle all the paperwork, ensuring a hassle-free launch for your venture.",
    icon: Building2,
    color: "text-[#0C6CE8]",
    bgColor: "bg-[#0C6CE8]/10",
    gradient: "from-[#0C6CE8] to-[#0C6CE8]/80",
    offerings: [
      { title: "Private Limited Registration", description: "Ideal for startups looking to raise funds and scale." },
      { title: "LLP Registration", description: "Perfect for professional firms and small businesses." },
      { title: "One Person Company (OPC)", description: "Best for solo entrepreneurs who want limited liability." },
      { title: "Partnership Firm", description: "Simple structure for small businesses with multiple owners." },
      { title: "GST Registration", description: "Mandatory tax registration for businesses." },
      { title: "MSME / Udyam Registration", description: "Unlock government benefits for small businesses." },
    ],
    benefits: [
      "Expert guidance on choosing the right structure",
      "Complete documentation support",
      "Fast-track registration process",
      "Post-incorporation compliance assistance",
    ],
    process: [
      { title: "Consultation", description: "We understand your business needs and recommend the best structure." },
      { title: "Documentation", description: "Collection and verification of all required documents." },
      { title: "Application Filing", description: "Submission of forms to the Registrar of Companies (ROC)." },
      { title: "Incorporation", description: "Receipt of Certificate of Incorporation and other documents." },
    ],
    faqs: [
      { question: "How long does it take to register a Private Limited Company?", answer: "Typically, it takes 10-15 working days, subject to government processing times." },
      { question: "What documents are required?", answer: "PAN card, Aadhaar card, bank statement, and address proof for all directors/shareholders." },
      { question: "Do I need a physical office?", answer: "Yes, a registered office address is mandatory, but it can be a residential address initially." },
    ],
  },
  {
    id: "accounting-compliance",
    title: "Accounting & Compliance",
    slug: "accounting-compliance",
    description: "Stay compliant and keep your finances in order with our expert accounting services.",
    longDescription: "Focus on growing your business while we handle your books and compliance. From daily accounting to annual filings, our team of experts ensures your financial records are accurate and you stay on the right side of the law.",
    icon: Calculator,
    color: "text-[#62C834]",
    bgColor: "bg-[#62C834]/10",
    gradient: "from-[#62C834] to-[#62C834]/80",
    offerings: [
      { title: "GST Filing", description: "Monthly/Quarterly GST return filing." },
      { title: "Bookkeeping", description: "Day-to-day maintenance of financial records." },
      { title: "ROC Filing", description: "Annual compliance for companies and LLPs." },
      { title: "Income Tax Returns", description: "Filing of annual income tax returns." },
      { title: "Audit Support", description: "Assistance during statutory and tax audits." },
      { title: "Compliance Calendar", description: "Tracking and reminders for all due dates." },
    ],
    benefits: [
      "Avoid penalties and legal issues",
      "Accurate financial reporting",
      "Timely filing of returns",
      "Expert tax planning advice",
    ],
    process: [
      { title: "Onboarding", description: "Understanding your business model and accounting needs." },
      { title: "Setup", description: "Setting up accounting software and processes." },
      { title: "Monthly Processing", description: "Regular recording of transactions and reconciliation." },
      { title: "Reporting & Filing", description: "Generation of reports and filing of returns." },
    ],
    faqs: [
      { question: "Do I need to file GST returns if I have no sales?", answer: "Yes, a NIL return must be filed to avoid penalties." },
      { question: "What is the due date for ROC filing?", answer: "For most companies, it is within 30 days of the AGM (Annual General Meeting)." },
    ],
  },
  {
    id: "branding-creative",
    title: "Branding & Creative Services",
    slug: "branding-creative",
    description: "Build a strong brand identity that resonates with your audience.",
    longDescription: "Your brand is more than just a logo; it's the face of your business. Our creative team helps you build a cohesive and memorable brand identity that stands out in the market and connects with your target audience.",
    icon: Palette,
    color: "text-[#FF8A00]",
    bgColor: "bg-[#FF8A00]/10",
    gradient: "from-[#FF8A00] to-[#FF8A00]/80",
    offerings: [
      { title: "Logo Design", description: "Unique and memorable logo concepts." },
      { title: "Brand Identity", description: "Complete visual language including colors and fonts." },
      { title: "Business Cards & Stationery", description: "Professional designs for print materials." },
      { title: "Packaging Design", description: "Attractive packaging for your products." },
      { title: "Social Media Kit", description: "Templates and assets for social media profiles." },
    ],
    benefits: [
      "Professional and consistent look",
      "Increased brand recognition",
      "Better customer trust",
      "Competitive advantage",
    ],
    process: [
      { title: "Discovery", description: "Understanding your brand values and target audience." },
      { title: "Concept", description: "Creating initial design concepts and mood boards." },
      { title: "Refinement", description: "Iterating based on your feedback." },
      { title: "Delivery", description: "Providing final files in all necessary formats." },
    ],
    faqs: [
      { question: "How many logo options will I get?", answer: "We typically provide 3-5 initial concepts to choose from." },
      { question: "Do I get the source files?", answer: "Yes, we provide all source files (AI, EPS, PDF) upon project completion." },
    ],
  },
  {
    id: "digital-marketing",
    title: "Digital Marketing",
    slug: "digital-marketing",
    description: "Grow your online presence and reach more customers with our digital marketing strategies.",
    longDescription: "In today's digital age, having a strong online presence is crucial. We help you reach your target audience, generate leads, and convert them into loyal customers through data-driven digital marketing strategies.",
    icon: Megaphone,
    color: "text-[#0C6CE8]",
    bgColor: "bg-[#0C6CE8]/10",
    gradient: "from-[#0C6CE8] to-[#0C6CE8]/80",
    offerings: [
      { title: "Website Creation", description: "Responsive and SEO-friendly websites." },
      { title: "SEO (Search Engine Optimization)", description: "Ranking your website higher on Google." },
      { title: "Social Media Management", description: "Engaging content for your social channels." },
      { title: "Performance Marketing", description: "Paid ads on Google, Facebook, and Instagram." },
      { title: "Content Marketing", description: "Blogs, articles, and other valuable content." },
    ],
    benefits: [
      "Increased website traffic",
      "Higher lead generation",
      "Better brand visibility",
      "Measurable ROI",
    ],
    process: [
      { title: "Audit", description: "Analyzing your current online presence." },
      { title: "Strategy", description: "Developing a customized marketing plan." },
      { title: "Execution", description: "Implementing campaigns and creating content." },
      { title: "Optimization", description: "Monitoring performance and making adjustments." },
    ],
    faqs: [
      { question: "How long does SEO take to show results?", answer: "SEO is a long-term strategy; typically, you start seeing results in 3-6 months." },
      { question: "Which social media platforms should I be on?", answer: "It depends on your target audience. We help you identify the best platforms for your business." },
    ],
  },
  {
    id: "it-software",
    title: "IT & Software Solutions",
    slug: "it-software",
    description: "Leverage technology to streamline your operations and boost productivity.",
    longDescription: "Technology is the backbone of modern business. We provide robust IT solutions, from custom software development to ERP implementation, helping you automate processes and improve efficiency.",
    icon: Code,
    color: "text-[#62C834]",
    bgColor: "bg-[#62C834]/10",
    gradient: "from-[#62C834] to-[#62C834]/80",
    offerings: [
      { title: "Billing Software", description: "Easy-to-use software for invoicing and inventory." },
      { title: "ERP Setup", description: "Enterprise Resource Planning for comprehensive management." },
      { title: "Custom App Development", description: "Mobile and web apps tailored to your needs." },
      { title: "IT Support", description: "Ongoing technical support and maintenance." },
      { title: "Cloud Solutions", description: "Migration and management of cloud infrastructure." },
    ],
    benefits: [
      "Improved operational efficiency",
      "Data security and backup",
      "Scalable solutions",
      "Reduced manual errors",
    ],
    process: [
      { title: "Requirement Analysis", description: "Understanding your technical needs." },
      { title: "Solution Design", description: "Architecting the right software solution." },
      { title: "Development/Implementation", description: "Building or setting up the system." },
      { title: "Training & Support", description: "Training your team and providing ongoing support." },
    ],
    faqs: [
      { question: "Can you customize existing software?", answer: "Yes, depending on the software's flexibility, we can customize it to fit your workflow." },
      { question: "Do you provide support after development?", answer: "Absolutely, we offer various support packages to ensure smooth operation." },
    ],
  },
  {
    id: "licensing",
    title: "Business Licensing & Approvals",
    slug: "licensing",
    description: "Navigate the regulatory landscape with our licensing and approval services.",
    longDescription: "Getting the necessary licenses can be a tedious process. We handle the bureaucracy for you, obtaining all required government approvals and licenses so you can operate your business legally and without interruption.",
    icon: FileCheck,
    color: "text-[#FF8A00]",
    bgColor: "bg-[#FF8A00]/10",
    gradient: "from-[#FF8A00] to-[#FF8A00]/80",
    offerings: [
      { title: "FSSAI Registration", description: "Food safety license for food businesses." },
      { title: "Trade License", description: "Municipal license to conduct trade." },
      { title: "Import Export Code (IEC)", description: "Mandatory for import/export businesses." },
      { title: "Shops & Establishment", description: "Registration for shops and commercial establishments." },
      { title: "Local Approvals", description: "Panchayat/Municipality permits." },
    ],
    benefits: [
      "Legal compliance",
      "Avoidance of fines and closures",
      "Smooth business operations",
      "Credibility with customers",
    ],
    process: [
      { title: "Assessment", description: "Identifying required licenses for your business type." },
      { title: "Documentation", description: "Preparing necessary documents and forms." },
      { title: "Submission", description: "Filing applications with respective authorities." },
      { title: "Follow-up", description: "Tracking status and handling queries." },
    ],
    faqs: [
      { question: "Is FSSAI mandatory for home bakers?", answer: "Yes, any food business operator, including home bakers, requires FSSAI registration." },
      { question: "Does IEC expire?", answer: "No, IEC is a lifetime registration and does not require renewal." },
    ],
  },
  {
    id: "hr-recruitment",
    title: "HR & Recruitment",
    slug: "hr-recruitment",
    description: "Build a winning team with our HR and recruitment solutions.",
    longDescription: "People are your biggest asset. We help you find the right talent and manage your workforce effectively. From recruitment to payroll, we handle your HR functions so you can focus on leadership.",
    icon: Users,
    color: "text-[#0C6CE8]",
    bgColor: "bg-[#0C6CE8]/10",
    gradient: "from-[#0C6CE8] to-[#0C6CE8]/80",
    offerings: [
      { title: "Talent Sourcing", description: "Finding and screening potential candidates." },
      { title: "Payroll Setup", description: "Setting up salary structures and processing." },
      { title: "Employee Onboarding", description: "Smooth integration of new hires." },
      { title: "HR Policies", description: "Drafting employee handbooks and policies." },
      { title: "Compliance", description: "PF, ESI, and other labor law compliance." },
    ],
    benefits: [
      "Access to quality talent",
      "Compliant HR practices",
      "Reduced turnover",
      "Efficient payroll management",
    ],
    process: [
      { title: "Needs Assessment", description: "Defining job roles and requirements." },
      { title: "Sourcing", description: "Advertising and searching for candidates." },
      { title: "Screening", description: "Interviewing and shortlisting." },
      { title: "Placement", description: "Final selection and onboarding." },
    ],
    faqs: [
      { question: "Do you handle background checks?", answer: "Yes, we can conduct background verification for selected candidates." },
      { question: "Can you help with payroll for a small team?", answer: "Yes, we offer payroll services for teams of all sizes." },
    ],
  },
  {
    id: "consulting",
    title: "Business Consulting",
    slug: "consulting",
    description: "Strategic advice to help you make informed decisions and achieve growth.",
    longDescription: "Every business faces challenges. Our consultants provide expert advice and strategic planning to help you overcome obstacles, optimize operations, and identify new growth opportunities.",
    icon: TrendingUp,
    color: "text-[#62C834]",
    bgColor: "bg-[#62C834]/10",
    gradient: "from-[#62C834] to-[#62C834]/80",
    offerings: [
      { title: "Strategy Consulting", description: "Long-term business planning." },
      { title: "Market Analysis", description: "Researching market trends and competition." },
      { title: "Financial Planning", description: "Budgeting and financial forecasting." },
      { title: "Startup Guidance", description: "Mentorship for early-stage startups." },
      { title: "Process Optimization", description: "Improving operational efficiency." },
    ],
    benefits: [
      "Expert perspective",
      "Data-driven decisions",
      "Improved profitability",
      "Clear roadmap for growth",
    ],
    process: [
      { title: "Diagnosis", description: "Analyzing current business state and challenges." },
      { title: "Analysis", description: "Deep dive into data and market research." },
      { title: "Recommendations", description: "Proposing strategic solutions." },
      { title: "Implementation Support", description: "Helping execute the strategy." },
    ],
    faqs: [
      { question: "Is consulting only for large companies?", answer: "No, we work with businesses of all sizes, including startups and SMEs." },
      { question: "How do you charge for consulting?", answer: "We offer project-based or retainer-based pricing models." },
    ],
  },
  {
    id: "funding",
    title: "Funding & Investment Support",
    slug: "funding",
    description: "Secure the capital you need to scale your business.",
    longDescription: "Raising funds is a critical step for many startups. We help you prepare for investment, create compelling pitch decks, and connect with potential investors to secure the funding you need.",
    icon: DollarSign,
    color: "text-[#FF8A00]",
    bgColor: "bg-[#FF8A00]/10",
    gradient: "from-[#FF8A00] to-[#FF8A00]/80",
    offerings: [
      { title: "Pitch Deck Creation", description: "Designing professional investor presentations." },
      { title: "Business Plan", description: "Detailed financial and operational planning." },
      { title: "Investor Connect", description: "Introductions to angel investors and VCs." },
      { title: "Valuation", description: "Determining the fair value of your business." },
      { title: "Due Diligence Support", description: "Preparing for investor scrutiny." },
    ],
    benefits: [
      "Investment-ready documents",
      "Access to investor network",
      "Better negotiation position",
      "Structured fundraising process",
    ],
    process: [
      { title: "Preparation", description: "Refining business model and documents." },
      { title: "Valuation", description: "Assessing funding requirements and equity." },
      { title: "Outreach", description: "Connecting with relevant investors." },
      { title: "Closing", description: "Negotiating terms and completing paperwork." },
    ],
    faqs: [
      { question: "Do you guarantee funding?", answer: "While we cannot guarantee funding, we significantly improve your chances through professional preparation." },
      { question: "What stage startups do you help?", answer: "We assist startups from seed stage to Series A." },
    ],
  },
  {
    id: "legal",
    title: "Legal Support",
    slug: "legal",
    description: "Protect your business with solid legal agreements and advice.",
    longDescription: "Legal issues can derail a business. We provide comprehensive legal support, drafting contracts, protecting intellectual property, and ensuring your business interests are safeguarded.",
    icon: Scale,
    color: "text-[#555555]",
    bgColor: "bg-[#555555]/10",
    gradient: "from-[#555555] to-[#555555]/80",
    offerings: [
      { title: "Contracts & Agreements", description: "Drafting and vetting legal documents." },
      { title: "Trademark Registration", description: "Protecting your brand name and logo." },
      { title: "MOUs", description: "Memorandum of Understanding for partnerships." },
      { title: "Legal Advisory", description: "General legal counsel for business matters." },
      { title: "Dispute Resolution", description: "Assistance in resolving business disputes." },
    ],
    benefits: [
      "Legal protection",
      "Risk mitigation",
      "Clear business relationships",
      "IP security",
    ],
    process: [
      { title: "Consultation", description: "Understanding legal requirements." },
      { title: "Drafting", description: "Creating legal documents." },
      { title: "Review", description: "Refining terms and conditions." },
      { title: "Execution", description: "Finalizing and signing documents." },
    ],
    faqs: [
      { question: "Why do I need a trademark?", answer: "A trademark protects your brand identity from being used by others." },
      { question: "Are online legal templates enough?", answer: "Templates may not cover specific risks; customized agreements are always safer." },
    ],
  },
]
